<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.2.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,.
 *
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */

namespace MultiFlexi\Api\Server;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractGdprApi Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractGdprApi
{
    /**
     * GET downloadDataExport
     * Summary: Download personal data export file
     * Notes: Download previously requested personal data export using secure token
     * Output-Formats: [application/json, text/plain].
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function downloadDataExport(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $token = (\array_key_exists('token', $queryParams)) ? $queryParams['token'] : null;
        $message = 'How about implementing downloadDataExport as a GET method in MultiFlexi\\Api\\Server\\GdprApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET requestDataExport
     * Summary: Request personal data export (GDPR Article 15)
     * Notes: Request export of all personal data associated with the authenticated user
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function requestDataExport(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $action = (\array_key_exists('action', $queryParams)) ? $queryParams['action'] : null;
        $format = (\array_key_exists('format', $queryParams)) ? $queryParams['format'] : null;
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $message = 'How about implementing requestDataExport as a GET method in MultiFlexi\\Api\\Server\\GdprApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST requestDataExportPost
     * Summary: Request personal data export (GDPR Article 15)
     * Notes: Request export of all personal data associated with the authenticated user
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function requestDataExportPost(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = 'How about implementing requestDataExportPost as a POST method in MultiFlexi\\Api\\Server\\GdprApi class?';

        throw new HttpNotImplementedException($request, $message);
    }
}
