<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,.
 *
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */

namespace MultiFlexi\Api\Server;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractEventsourceApi Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractEventsourceApi
{
    /**
     * DELETE deleteEventSourceById
     * Summary: Delete EventSource by ID
     * Notes: Remove an EventSource.
     *
     * @param ServerRequestInterface $request       Request
     * @param ResponseInterface      $response      Response
     * @param int                    $eventSourceId ID of EventSource to delete
     * @param string                 $suffix        force format suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteEventSourceById(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $eventSourceId,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $message = 'How about implementing deleteEventSourceById as a DELETE method in MultiFlexi\\Api\\Server\\EventsourceApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getEventSourceById
     * Summary: Get EventSource by ID
     * Notes: Returns a single EventSource (webhook adapter database connection)
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request       Request
     * @param ResponseInterface      $response      Response
     * @param int                    $eventSourceId ID of EventSource to return
     * @param string                 $suffix        force format suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getEventSourceById(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $eventSourceId,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $message = 'How about implementing getEventSourceById as a GET method in MultiFlexi\\Api\\Server\\EventsourceApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET listEventSources
     * Summary: Show All EventSources
     * Notes: All EventSources registered
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string                 $suffix   force format suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function listEventSources(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $offset = (\array_key_exists('offset', $queryParams)) ? $queryParams['offset'] : null;
        $order = (\array_key_exists('order', $queryParams)) ? $queryParams['order'] : null;
        $message = 'How about implementing listEventSources as a GET method in MultiFlexi\\Api\\Server\\EventsourceApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST setEventSourceById
     * Summary: Create or Update EventSource
     * Notes: Create or Update EventSource (webhook adapter database connection)
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function setEventSourceById(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $eventSourceId = (\array_key_exists('eventSourceId', $queryParams)) ? $queryParams['eventSourceId'] : null;
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $body = $request->getParsedBody();
        $message = 'How about implementing setEventSourceById as a POST method in MultiFlexi\\Api\\Server\\EventsourceApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST testEventSourceConnection
     * Summary: Test EventSource connection
     * Notes: Test the database connection of an EventSource
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request       Request
     * @param ResponseInterface      $response      Response
     * @param int                    $eventSourceId ID of EventSource to test
     * @param string                 $suffix        force format suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function testEventSourceConnection(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $eventSourceId,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $message = 'How about implementing testEventSourceConnection as a POST method in MultiFlexi\\Api\\Server\\EventsourceApi class?';

        throw new HttpNotImplementedException($request, $message);
    }
}
