<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,.
 *
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */

namespace MultiFlexi\Api\Server;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractUserCompanyApi Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractUserCompanyApi
{
    /**
     * POST assignUserToCompany
     * Summary: Assign a user to a company
     * Notes: Create or update the role of a user in a company (upsert)
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request   Request
     * @param ResponseInterface      $response  Response
     * @param int                    $companyId ID of the company
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function assignUserToCompany(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $companyId
    ): ResponseInterface {
        $body = $request->getParsedBody();
        $message = 'How about implementing assignUserToCompany as a POST method in MultiFlexi\\Api\\Server\\UserCompanyApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET listCompanyUsers
     * Summary: List users assigned to a company
     * Notes: Returns users with their assigned roles in the given company
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request   Request
     * @param ResponseInterface      $response  Response
     * @param int                    $companyId ID of the company
     * @param string                 $suffix    force format suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function listCompanyUsers(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $companyId,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $offset = (\array_key_exists('offset', $queryParams)) ? $queryParams['offset'] : null;
        $order = (\array_key_exists('order', $queryParams)) ? $queryParams['order'] : null;
        $message = 'How about implementing listCompanyUsers as a GET method in MultiFlexi\\Api\\Server\\UserCompanyApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE unassignUserFromCompany
     * Summary: Remove a user from a company
     * Notes: Unassign the specified user from the company
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request   Request
     * @param ResponseInterface      $response  Response
     * @param int                    $companyId ID of the company
     * @param int                    $userId    ID of the user to remove
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function unassignUserFromCompany(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $companyId,
        int $userId
    ): ResponseInterface {
        $message = 'How about implementing unassignUserFromCompany as a DELETE method in MultiFlexi\\Api\\Server\\UserCompanyApi class?';

        throw new HttpNotImplementedException($request, $message);
    }
}
