<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,.
 *
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */

namespace MultiFlexi\Api\Server;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractEventruleApi Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractEventruleApi
{
    /**
     * DELETE deleteEventRuleById
     * Summary: Delete EventRule by ID
     * Notes: Remove an EventRule.
     *
     * @param ServerRequestInterface $request     Request
     * @param ResponseInterface      $response    Response
     * @param int                    $eventRuleId ID of EventRule to delete
     * @param string                 $suffix      force format suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteEventRuleById(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $eventRuleId,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $message = 'How about implementing deleteEventRuleById as a DELETE method in MultiFlexi\\Api\\Server\\EventruleApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getEventRuleById
     * Summary: Get EventRule by ID
     * Notes: Returns a single EventRule (event-to-RunTemplate mapping)
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request     Request
     * @param ResponseInterface      $response    Response
     * @param int                    $eventRuleId ID of EventRule to return
     * @param string                 $suffix      force format suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getEventRuleById(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $eventRuleId,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $message = 'How about implementing getEventRuleById as a GET method in MultiFlexi\\Api\\Server\\EventruleApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET listEventRules
     * Summary: Show All EventRules
     * Notes: All EventRules registered
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string                 $suffix   force format suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function listEventRules(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $offset = (\array_key_exists('offset', $queryParams)) ? $queryParams['offset'] : null;
        $order = (\array_key_exists('order', $queryParams)) ? $queryParams['order'] : null;
        $message = 'How about implementing listEventRules as a GET method in MultiFlexi\\Api\\Server\\EventruleApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST setEventRuleById
     * Summary: Create or Update EventRule
     * Notes: Create or Update EventRule (event-to-RunTemplate mapping)
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function setEventRuleById(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $eventRuleId = (\array_key_exists('eventRuleId', $queryParams)) ? $queryParams['eventRuleId'] : null;
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $body = $request->getParsedBody();
        $message = 'How about implementing setEventRuleById as a POST method in MultiFlexi\\Api\\Server\\EventruleApi class?';

        throw new HttpNotImplementedException($request, $message);
    }
}
