<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,.
 *
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */

namespace MultiFlexi\Api\Server;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractCredentialTypeApi Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractCredentialTypeApi
{
    /**
     * GET getAllCredentialTypes
     * Summary: Get All Credential Types
     * Notes: Retrieve all credential types
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string                 $suffix   force format suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getAllCredentialTypes(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $offset = (\array_key_exists('offset', $queryParams)) ? $queryParams['offset'] : null;
        $order = (\array_key_exists('order', $queryParams)) ? $queryParams['order'] : null;
        $message = 'How about implementing getAllCredentialTypes as a GET method in MultiFlexi\\Api\\Server\\CredentialTypeApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getCredentialType
     * Summary: Get Credential Type by ID
     * Notes: Retrieve credential type by ID
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request          Request
     * @param ResponseInterface      $response         Response
     * @param int                    $credentialTypeID ID of Credential Type to return
     * @param string                 $suffix           force format suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getCredentialType(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $credentialTypeID,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $message = 'How about implementing getCredentialType as a GET method in MultiFlexi\\Api\\Server\\CredentialTypeApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * POST updateCredentialType
     * Summary: Update Credential Type
     * Notes: Update credential type
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request          Request
     * @param ResponseInterface      $response         Response
     * @param int                    $credentialTypeID ID of Credential Type to return
     * @param string                 $suffix           force format suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function updateCredentialType(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $credentialTypeID,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $message = 'How about implementing updateCredentialType as a POST method in MultiFlexi\\Api\\Server\\CredentialTypeApi class?';

        throw new HttpNotImplementedException($request, $message);
    }
}
