<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.4.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,.
 *
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */

namespace MultiFlexi\Api\Server;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractAuditlogApi Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractAuditlogApi
{
    /**
     * GET getAuditLogById
     * Summary: Get Audit Log entry by ID
     * Notes: Returns a single audit log entry.
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request    Request
     * @param ResponseInterface      $response   Response
     * @param int                    $auditLogId auditLogId
     * @param string                 $suffix     suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getAuditLogById(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $auditLogId,
        string $suffix
    ): ResponseInterface {
        $message = 'How about implementing getAuditLogById as a GET method in MultiFlexi\\Api\\Server\\AuditlogApi class?';

        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET listAuditLog
     * Summary: List Audit Log entries
     * Notes: Returns entity create/update/delete audit entries, recorded automatically for every model saved or deleted via the web UI, CLI, or REST API.
     * Output-Formats: [application/json].
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param string                 $suffix   suffix
     *
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function listAuditLog(
        ServerRequestInterface $request,
        ResponseInterface $response,
        string $suffix
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $userId = (\array_key_exists('user_id', $queryParams)) ? $queryParams['user_id'] : null;
        $entityType = (\array_key_exists('entity_type', $queryParams)) ? $queryParams['entity_type'] : null;
        $entityId = (\array_key_exists('entity_id', $queryParams)) ? $queryParams['entity_id'] : null;
        $action = (\array_key_exists('action', $queryParams)) ? $queryParams['action'] : null;
        $from = (\array_key_exists('from', $queryParams)) ? $queryParams['from'] : null;
        $to = (\array_key_exists('to', $queryParams)) ? $queryParams['to'] : null;
        $limit = (\array_key_exists('limit', $queryParams)) ? $queryParams['limit'] : null;
        $message = 'How about implementing listAuditLog as a GET method in MultiFlexi\\Api\\Server\\AuditlogApi class?';

        throw new HttpNotImplementedException($request, $message);
    }
}
