<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace MultiFlexi\Api\ApiServer;

use PHPUnit\Framework\TestCase;

/**
 * CompanyApiTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\ApiServer\CompanyApi
 */
class CompanyApiTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test case for getCompanyById.
     *
     * Get Company by ID.
     *
     * @covers ::getCompanyById
     */
    public function testGetCompanyById(): void
    {
        self::markTestIncomplete(
            'Test of "getCompanyById" method has not been implemented yet.',
        );
    }

    /**
     * Test case for listCompanies.
     *
     * Show All Companies.
     *
     * @covers ::listCompanies
     */
    public function testListCompanies(): void
    {
        self::markTestIncomplete(
            'Test of "listCompanies" method has not been implemented yet.',
        );
    }

    /**
     * Test case for setCompanyById.
     *
     * Create or Update Company.
     *
     * @covers ::setCompanyById
     */
    public function testSetCompanyById(): void
    {
        self::markTestIncomplete(
            'Test of "setCompanyById" method has not been implemented yet.',
        );
    }
}
