<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.1.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace MultiFlexi\Api\Server;

use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Server\DefaultApi
 */
class DefaultApiTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test case for getAllCredentialTypes.
     *
     * Get All Credential Types.
     *
     * @covers ::getAllCredentialTypes
     */
    public function testGetAllCredentialTypes(): void
    {
        self::markTestIncomplete(
            'Test of "getAllCredentialTypes" method has not been implemented yet.',
        );
    }

    /**
     * Test case for getAllTopics.
     *
     * Get All Topics.
     *
     * @covers ::getAllTopics
     */
    public function testGetAllTopics(): void
    {
        self::markTestIncomplete(
            'Test of "getAllTopics" method has not been implemented yet.',
        );
    }

    /**
     * Test case for getAllUserCredentials.
     *
     * Get All User Credentials.
     *
     * @covers ::getAllUserCredentials
     */
    public function testGetAllUserCredentials(): void
    {
        self::markTestIncomplete(
            'Test of "getAllUserCredentials" method has not been implemented yet.',
        );
    }

    /**
     * Test case for getApiIndex.
     *
     * Endpoints listing.
     *
     * @covers ::getApiIndex
     */
    public function testGetApiIndex(): void
    {
        self::markTestIncomplete(
            'Test of "getApiIndex" method has not been implemented yet.',
        );
    }

    /**
     * Test case for getCredential.
     *
     * Get User Credentials.
     *
     * @covers ::getCredential
     */
    public function testGetCredential(): void
    {
        self::markTestIncomplete(
            'Test of "getCredential" method has not been implemented yet.',
        );
    }

    /**
     * Test case for getCredentialType.
     *
     * Get Credential Type by ID.
     *
     * @covers ::getCredentialType
     */
    public function testGetCredentialType(): void
    {
        self::markTestIncomplete(
            'Test of "getCredentialType" method has not been implemented yet.',
        );
    }

    /**
     * Test case for getTopic.
     *
     * Get Topic by ID.
     *
     * @covers ::getTopic
     */
    public function testGetTopic(): void
    {
        self::markTestIncomplete(
            'Test of "getTopic" method has not been implemented yet.',
        );
    }

    /**
     * Test case for loginSuffixGet.
     *
     * Return User's token.
     *
     * @covers ::loginSuffixGet
     */
    public function testLoginSuffixGet(): void
    {
        self::markTestIncomplete(
            'Test of "loginSuffixGet" method has not been implemented yet.',
        );
    }

    /**
     * Test case for loginSuffixPost.
     *
     * Return User's token.
     *
     * @covers ::loginSuffixPost
     */
    public function testLoginSuffixPost(): void
    {
        self::markTestIncomplete(
            'Test of "loginSuffixPost" method has not been implemented yet.',
        );
    }

    /**
     * Test case for pingSuffixGet.
     *
     * job heartbeat operation.
     *
     * @covers ::pingSuffixGet
     */
    public function testPingSuffixGet(): void
    {
        self::markTestIncomplete(
            'Test of "pingSuffixGet" method has not been implemented yet.',
        );
    }

    /**
     * Test case for rootGet.
     *
     * Redirect to index.
     *
     * @covers ::rootGet
     */
    public function testRootGet(): void
    {
        self::markTestIncomplete(
            'Test of "rootGet" method has not been implemented yet.',
        );
    }

    /**
     * Test case for statusSuffixGet.
     *
     * Get API status.
     *
     * @covers ::statusSuffixGet
     */
    public function testStatusSuffixGet(): void
    {
        self::markTestIncomplete(
            'Test of "statusSuffixGet" method has not been implemented yet.',
        );
    }

    /**
     * Test case for updateCredentialType.
     *
     * Update Credential Type.
     *
     * @covers ::updateCredentialType
     */
    public function testUpdateCredentialType(): void
    {
        self::markTestIncomplete(
            'Test of "updateCredentialType" method has not been implemented yet.',
        );
    }

    /**
     * Test case for updateCredentials.
     *
     * Update Credentials.
     *
     * @covers ::updateCredentials
     */
    public function testUpdateCredentials(): void
    {
        self::markTestIncomplete(
            'Test of "updateCredentials" method has not been implemented yet.',
        );
    }

    /**
     * Test case for updateTopic.
     *
     * Update Topic.
     *
     * @covers ::updateTopic
     */
    public function testUpdateTopic(): void
    {
        self::markTestIncomplete(
            'Test of "updateTopic" method has not been implemented yet.',
        );
    }
}
