<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.0.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace MultiFlexi\Api\ApiServer;

use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\ApiServer\DefaultApi
 */
class DefaultApiTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test case for getApiIndex.
     *
     * Endpoints listing.
     *
     * @covers ::getApiIndex
     */
    public function testGetApiIndex(): void
    {
        self::markTestIncomplete(
            'Test of "getApiIndex" method has not been implemented yet.',
        );
    }

    /**
     * Test case for loginSuffixGet.
     *
     * Return User's token.
     *
     * @covers ::loginSuffixGet
     */
    public function testLoginSuffixGet(): void
    {
        self::markTestIncomplete(
            'Test of "loginSuffixGet" method has not been implemented yet.',
        );
    }

    /**
     * Test case for loginSuffixPost.
     *
     * Return User's token.
     *
     * @covers ::loginSuffixPost
     */
    public function testLoginSuffixPost(): void
    {
        self::markTestIncomplete(
            'Test of "loginSuffixPost" method has not been implemented yet.',
        );
    }

    /**
     * Test case for pingSuffixGet.
     *
     * job heartbeat operation.
     *
     * @covers ::pingSuffixGet
     */
    public function testPingSuffixGet(): void
    {
        self::markTestIncomplete(
            'Test of "pingSuffixGet" method has not been implemented yet.',
        );
    }

    /**
     * Test case for rootGet.
     *
     * Redirect to index.
     *
     * @covers ::rootGet
     */
    public function testRootGet(): void
    {
        self::markTestIncomplete(
            'Test of "rootGet" method has not been implemented yet.',
        );
    }
}
