<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace MultiFlexi\Api\Server;

use PHPUnit\Framework\TestCase;

/**
 * RuntemplateApiTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Server\RuntemplateApi
 */
class RuntemplateApiTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test case for getRunTemplateById.
     *
     * Get RunTemplate by ID.
     *
     * @covers ::getRunTemplateById
     */
    public function testGetRunTemplateById(): void
    {
        self::markTestIncomplete(
            'Test of "getRunTemplateById" method has not been implemented yet.',
        );
    }

    /**
     * Test case for listRunTemplates.
     *
     * Show All RunTemplates.
     *
     * @covers ::listRunTemplates
     */
    public function testListRunTemplates(): void
    {
        self::markTestIncomplete(
            'Test of "listRunTemplates" method has not been implemented yet.',
        );
    }

    /**
     * Test case for setRunTemplateById.
     *
     * Create or Update RunTemplate.
     *
     * @covers ::setRunTemplateById
     */
    public function testSetRunTemplateById(): void
    {
        self::markTestIncomplete(
            'Test of "setRunTemplateById" method has not been implemented yet.',
        );
    }

    /**
     * Test case for updateRunTemplateById.
     *
     * Update RunTemplate by ID.
     *
     * @covers ::updateRunTemplateById
     */
    public function testUpdateRunTemplateById(): void
    {
        self::markTestIncomplete(
            'Test of "updateRunTemplateById" method has not been implemented yet.',
        );
    }
}
