<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace MultiFlexi\Api\Server;

use PHPUnit\Framework\TestCase;

/**
 * TaskApiTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Server\TaskApi
 */
class TaskApiTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test case for getTaskById.
     *
     * Get Task by ID.
     *
     * @covers ::getTaskById
     */
    public function testGetTaskById(): void
    {
        self::markTestIncomplete('Test of "getTaskById" method has not been implemented yet.');
    }

    /**
     * Test case for listTasks.
     *
     * List Tasks.
     *
     * @covers ::listTasks
     */
    public function testListTasks(): void
    {
        self::markTestIncomplete('Test of "listTasks" method has not been implemented yet.');
    }
}
