<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.4.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator.
 */

namespace MultiFlexi\Api\Model;

use MultiFlexi\Api\BaseModel;

/**
 * AuditLogEntry.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
class AuditLogEntry extends BaseModel
{
    /**
     * @var string Models namespace.
     *             Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\MultiFlexi\Api\Model';

    /**
     * @var string Constant with OAS schema of current class.
     *             Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 1
    },
    "user_id" : {
      "type" : "integer",
      "description" : "ID of the user who performed the action; null for unattended/system actions (e.g. scheduler daemon)",
      "format" : "int64",
      "nullable" : true
    },
    "entity_type" : {
      "type" : "string",
      "description" : "Short class name of the audited entity, e.g. RunTemplate, Company, Credential",
      "nullable" : true,
      "example" : "RunTemplate"
    },
    "entity_id" : {
      "type" : "integer",
      "description" : "Primary key of the audited entity row",
      "format" : "int64",
      "nullable" : true
    },
    "action" : {
      "type" : "string",
      "nullable" : true,
      "enum" : [ "create", "update", "delete" ]
    },
    "event_description" : {
      "type" : "string",
      "description" : "Human-readable summary of the action"
    },
    "severity" : {
      "type" : "string",
      "enum" : [ "low", "medium", "high", "critical" ]
    },
    "additional_data" : {
      "type" : "object",
      "description" : "Extra context stored with the entry (e.g. the delete filter conditions)",
      "nullable" : true
    },
    "created_at" : {
      "type" : "string",
      "format" : "date-time"
    }
  }
}
SCHEMA;
}
