<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator.
 */

namespace MultiFlexi\Api\Model;

use MultiFlexi\Api\BaseModel;

/**
 * CompanyUser.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
class CompanyUser extends BaseModel
{
    /**
     * @var string Models namespace.
     *             Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\MultiFlexi\Api\Model';

    /**
     * @var string Constant with OAS schema of current class.
     *             Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "company_id" : {
      "type" : "integer",
      "description" : "Company ID",
      "format" : "int64",
      "example" : 1
    },
    "user_id" : {
      "type" : "integer",
      "description" : "User ID",
      "format" : "int64",
      "example" : 10
    },
    "role" : {
      "type" : "string",
      "description" : "Access role in the company (e.g. viewer, manager, admin)",
      "example" : "viewer",
      "default" : "viewer"
    },
    "created_at" : {
      "type" : "string",
      "description" : "Timestamp when the assignment was created",
      "format" : "date-time"
    }
  },
  "description" : "Many-to-many assignment of a user to a company with an access role"
}
SCHEMA;
}
