<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator.
 */

namespace MultiFlexi\Api\Model;

use MultiFlexi\Api\BaseModel;

/**
 * DataExportDataUserProfile.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
class DataExportDataUserProfile extends BaseModel
{
    /**
     * @var string Models namespace.
     *             Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\MultiFlexi\Api\Model';

    /**
     * @var string Constant with OAS schema of current class.
     *             Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "user_id" : {
      "type" : "integer",
      "example" : 42
    },
    "username" : {
      "type" : "string",
      "example" : "john.doe"
    },
    "email" : {
      "type" : "string",
      "format" : "email",
      "example" : "john.doe@example.com"
    },
    "first_name" : {
      "type" : "string",
      "example" : "John"
    },
    "last_name" : {
      "type" : "string",
      "example" : "Doe"
    },
    "account_enabled" : {
      "type" : "boolean",
      "example" : true
    },
    "account_created" : {
      "type" : "string",
      "format" : "date-time",
      "example" : "2023-01-15T10:30:00Z"
    },
    "last_updated" : {
      "type" : "string",
      "format" : "date-time",
      "nullable" : true,
      "example" : "2024-06-10T14:22:00Z"
    },
    "user_settings" : {
      "type" : "object",
      "description" : "User preference settings (if any)",
      "nullable" : true
    }
  }
}
SCHEMA;
}
