<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator.
 */

namespace MultiFlexi\Api\Model;

use MultiFlexi\Api\BaseModel;

/**
 * DataExportResponse.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
class DataExportResponse extends BaseModel
{
    /**
     * @var string Models namespace.
     *             Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\MultiFlexi\Api\Model';

    /**
     * @var string Constant with OAS schema of current class.
     *             Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "download_url", "expires_at", "format", "generated_at", "success" ],
  "type" : "object",
  "properties" : {
    "success" : {
      "type" : "boolean",
      "example" : true
    },
    "download_url" : {
      "type" : "string",
      "description" : "Secure download URL for the exported data",
      "format" : "uri",
      "example" : "/data-export.php?token=a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890123456"
    },
    "format" : {
      "type" : "string",
      "description" : "Format of the exported data",
      "example" : "json",
      "enum" : [ "json", "pdf" ]
    },
    "generated_at" : {
      "type" : "string",
      "description" : "ISO 8601 timestamp when the export was generated",
      "format" : "date-time",
      "example" : "2025-10-20T16:15:00Z"
    },
    "expires_at" : {
      "type" : "string",
      "description" : "ISO 8601 timestamp when the download link expires",
      "format" : "date-time",
      "example" : "2025-10-20T17:15:00Z"
    },
    "notification_sent" : {
      "type" : "boolean",
      "description" : "Whether email notification was sent to user",
      "example" : true
    }
  }
}
SCHEMA;
}
