<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.2.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator.
 */

namespace MultiFlexi\Api\Model;

use MultiFlexi\Api\BaseModel;

/**
 * DataExportDataExportMetadata.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
class DataExportDataExportMetadata extends BaseModel
{
    /**
     * @var string Models namespace.
     *             Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\MultiFlexi\Api\Model';

    /**
     * @var string Constant with OAS schema of current class.
     *             Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "data_controller", "export_date", "gdpr_article", "user_id" ],
  "type" : "object",
  "properties" : {
    "export_date" : {
      "type" : "string",
      "description" : "When the export was generated",
      "format" : "date-time",
      "example" : "2025-10-20T16:15:00Z"
    },
    "user_id" : {
      "type" : "integer",
      "description" : "ID of the user whose data is exported",
      "example" : 42
    },
    "export_version" : {
      "type" : "string",
      "description" : "Version of the export format",
      "example" : "1.0"
    },
    "gdpr_article" : {
      "type" : "string",
      "description" : "GDPR article reference",
      "example" : "Article 15 - Right of Access"
    },
    "data_controller" : {
      "type" : "string",
      "description" : "Name of the data controller",
      "example" : "MultiFlexi"
    },
    "retention_info" : {
      "type" : "string",
      "description" : "Data retention policy information",
      "example" : "Data is retained according to our privacy policy"
    },
    "contact_info" : {
      "type" : "string",
      "description" : "Contact information for data protection inquiries",
      "example" : "For questions about this export, contact your data protection officer"
    }
  }
}
SCHEMA;
}
