<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.2.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator.
 */

namespace MultiFlexi\Api\Model;

use MultiFlexi\Api\BaseModel;

/**
 * DataExportDataConsentRecordsConsentAuditTrailInner.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
class DataExportDataConsentRecordsConsentAuditTrailInner extends BaseModel
{
    /**
     * @var string Models namespace.
     *             Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\MultiFlexi\Api\Model';

    /**
     * @var string Constant with OAS schema of current class.
     *             Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "action" : {
      "type" : "string",
      "example" : "granted"
    },
    "consent_type" : {
      "type" : "string",
      "example" : "analytics"
    },
    "old_value" : {
      "type" : "object",
      "nullable" : true
    },
    "new_value" : {
      "type" : "object",
      "nullable" : true
    },
    "timestamp" : {
      "type" : "string",
      "format" : "date-time",
      "example" : "2024-05-15T16:45:00Z"
    },
    "ip_address" : {
      "type" : "string",
      "example" : "192.168.1.100"
    }
  }
}
SCHEMA;
}
