<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator.
 */

namespace MultiFlexi\Api\Model;

use MultiFlexi\Api\BaseModel;

/**
 * DataExportDataCompanyAssociationsInner.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
class DataExportDataCompanyAssociationsInner extends BaseModel
{
    /**
     * @var string Models namespace.
     *             Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\MultiFlexi\Api\Model';

    /**
     * @var string Constant with OAS schema of current class.
     *             Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "company_id" : {
      "type" : "integer",
      "example" : 15
    },
    "company_code" : {
      "type" : "string",
      "example" : "ACME001"
    },
    "company_name" : {
      "type" : "string",
      "example" : "ACME Corporation"
    },
    "company_identifier" : {
      "type" : "string",
      "nullable" : true,
      "example" : "12345678"
    },
    "enabled" : {
      "type" : "boolean",
      "example" : true
    },
    "associated_since" : {
      "type" : "string",
      "format" : "date-time",
      "example" : "2023-03-01T09:15:00Z"
    },
    "relationship_type" : {
      "type" : "string",
      "example" : "user_activity"
    }
  }
}
SCHEMA;
}
