<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator.
 */

namespace MultiFlexi\Api\Model;

use MultiFlexi\Api\BaseModel;

/**
 * EventSource.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
class EventSource extends BaseModel
{
    /**
     * @var string Models namespace.
     *             Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\MultiFlexi\Api\Model';

    /**
     * @var string Constant with OAS schema of current class.
     *             Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 1
    },
    "name" : {
      "maxLength" : 255,
      "type" : "string",
      "description" : "Human-readable name for this event source",
      "example" : "AbraFlexi Webhooks"
    },
    "adapter_type" : {
      "maxLength" : 128,
      "type" : "string",
      "description" : "Type of webhook adapter",
      "example" : "abraflexi-webhook-acceptor"
    },
    "db_connection" : {
      "maxLength" : 16,
      "type" : "string",
      "description" : "Database driver",
      "default" : "mysql",
      "enum" : [ "mysql", "pgsql", "sqlite" ]
    },
    "db_host" : {
      "maxLength" : 255,
      "type" : "string",
      "description" : "Database host",
      "default" : "localhost"
    },
    "db_port" : {
      "maxLength" : 8,
      "type" : "string",
      "description" : "Database port",
      "default" : "3306"
    },
    "db_database" : {
      "maxLength" : 128,
      "type" : "string",
      "description" : "Database name"
    },
    "db_username" : {
      "maxLength" : 128,
      "type" : "string",
      "description" : "Database username"
    },
    "db_password" : {
      "maxLength" : 255,
      "type" : "string",
      "description" : "Database password"
    },
    "poll_interval" : {
      "type" : "integer",
      "description" : "How often to poll for new changes (seconds)",
      "format" : "int32",
      "default" : 60
    },
    "enabled" : {
      "type" : "boolean",
      "description" : "Whether this source is active",
      "default" : true
    },
    "last_processed_id" : {
      "type" : "integer",
      "description" : "Last processed change inversion ID",
      "format" : "int64",
      "default" : 0
    },
    "created" : {
      "type" : "string",
      "format" : "date-time"
    },
    "modified" : {
      "type" : "string",
      "format" : "date-time"
    }
  }
}
SCHEMA;
}
