<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator.
 */

namespace MultiFlexi\Api\Model;

use MultiFlexi\Api\BaseModel;

/**
 * RunTemplate.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
class RunTemplate extends BaseModel
{
    /**
     * @var string Models namespace.
     *             Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\MultiFlexi\Api\Model';

    /**
     * @var string Constant with OAS schema of current class.
     *             Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 10
    },
    "app_id" : {
      "type" : "integer",
      "description" : "Application ID",
      "format" : "int64",
      "example" : 10
    },
    "company_id" : {
      "type" : "integer",
      "description" : "Company ID",
      "format" : "int64",
      "example" : 10
    },
    "interv" : {
      "maxLength" : 64,
      "type" : "string",
      "description" : "Execution interval code",
      "example" : "d",
      "enum" : [ "c", "n", "i", "h", "d", "w", "m", "y" ]
    },
    "prepared" : {
      "type" : "boolean",
      "description" : "Whether the RunTemplate is prepared for execution",
      "nullable" : true
    },
    "success" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "Success action configuration (unserialized)",
      "nullable" : true,
      "example" : {
        "Zabbix" : true,
        "Reschedule" : false,
        "WebHook" : false
      }
    },
    "fail" : {
      "type" : "object",
      "additionalProperties" : true,
      "description" : "Failure action configuration (unserialized)",
      "nullable" : true,
      "example" : {
        "Zabbix" : true,
        "Reschedule" : false,
        "WebHook" : false
      }
    },
    "name" : {
      "maxLength" : 250,
      "type" : "string",
      "description" : "RunTemplate name",
      "nullable" : true,
      "example" : "Daily Report Processing"
    },
    "delay" : {
      "type" : "integer",
      "description" : "Delay in seconds before job execution",
      "format" : "int32",
      "example" : 18000,
      "default" : 0
    },
    "executor" : {
      "maxLength" : 255,
      "type" : "string",
      "description" : "Executor type (Native, Docker, etc.)",
      "example" : "Native",
      "default" : "Native"
    },
    "active" : {
      "type" : "boolean",
      "description" : "Whether the RunTemplate is active",
      "example" : true,
      "default" : true
    },
    "cron" : {
      "maxLength" : 64,
      "type" : "string",
      "description" : "Cron expression for scheduling",
      "nullable" : true,
      "example" : "0 0 * * *"
    },
    "last_schedule" : {
      "type" : "string",
      "description" : "Last scheduled execution timestamp",
      "format" : "date-time",
      "nullable" : true,
      "example" : "2025-11-21T05:00:00Z"
    },
    "next_schedule" : {
      "type" : "string",
      "description" : "Next scheduled execution timestamp",
      "format" : "date-time",
      "nullable" : true
    },
    "note" : {
      "type" : "string",
      "description" : "Additional notes about the RunTemplate",
      "nullable" : true
    },
    "DatCreate" : {
      "type" : "string",
      "description" : "Creation timestamp",
      "format" : "date-time",
      "nullable" : true,
      "example" : "2025-11-13T16:37:56Z"
    },
    "DatSave" : {
      "type" : "string",
      "description" : "Last modification timestamp",
      "format" : "date-time",
      "nullable" : true,
      "example" : "2025-11-21T05:01:53Z"
    },
    "successfull_jobs_count" : {
      "type" : "integer",
      "description" : "Count of successful jobs",
      "format" : "int32",
      "example" : 9,
      "default" : 0
    },
    "failed_jobs_count" : {
      "type" : "integer",
      "description" : "Count of failed jobs",
      "format" : "int32",
      "example" : 1,
      "default" : 0
    }
  }
}
SCHEMA;
}
