<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator.
 */

namespace MultiFlexi\Api\Model;

use MultiFlexi\Api\BaseModel;

/**
 * Task.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */
class Task extends BaseModel
{
    /**
     * @var string Models namespace.
     *             Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\MultiFlexi\Api\Model';

    /**
     * @var string Constant with OAS schema of current class.
     *             Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "properties" : {
    "id" : {
      "type" : "integer",
      "format" : "int64",
      "example" : 1
    },
    "runtemplate_id" : {
      "type" : "integer",
      "description" : "FK to the RunTemplate that spawned this task",
      "format" : "int64"
    },
    "window_start" : {
      "type" : "string",
      "description" : "Start of the scheduling window",
      "format" : "date-time"
    },
    "window_end" : {
      "type" : "string",
      "description" : "End of the scheduling window",
      "format" : "date-time"
    },
    "deadline" : {
      "type" : "string",
      "description" : "Deadline by which the result must be ready",
      "format" : "date-time"
    },
    "state" : {
      "type" : "string",
      "description" : "Current task state",
      "enum" : [ "open", "running", "fulfilled", "fulfilled_late", "failed", "missed" ]
    },
    "fulfilled_by_job_id" : {
      "type" : "integer",
      "description" : "ID of the job that fulfilled this task",
      "format" : "int64",
      "nullable" : true
    },
    "fulfilled_at" : {
      "type" : "string",
      "description" : "When the task was fulfilled",
      "format" : "date-time",
      "nullable" : true
    },
    "attempts" : {
      "type" : "integer",
      "description" : "Number of job attempts made",
      "format" : "int32"
    },
    "created_at" : {
      "type" : "string",
      "format" : "date-time"
    },
    "jobs" : {
      "type" : "array",
      "description" : "Job attempt history (only present in single-task responses)",
      "items" : {
        "$ref" : "#/components/schemas/Job"
      }
    }
  }
}
SCHEMA;
}
