<?php

/**
 * MultiFlexi API
 * PHP version 8.1.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.4.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace MultiFlexi\Api\App;

/**
 * RegisterMiddlewares.
 *
 * Recommendations from template creator:
 *
 * There is no way to add route related middlewares here, add global ones. Route related middlewares
 * can be applied in \MultiFlexi\Api\App\RegisterRoutes class.
 *
 * I add middlewares by full class names(\Slim\Middleware\ErrorMiddleware::class) because that way
 * Slim initiates them with options from Container. They already configured, don't need to pass any
 * options manually.
 *
 * I don't use imports(eg. use Slim\Middleware\ErrorMiddleware) here because each package unlikely
 * be used in code twice. It helps to keep that file short and make Git history cleaner.
 *
 * This class declared as final because two classes with middlewares can cause confusion. Edit
 * template of this class or use your own implementation instead(overwrite index.php to import your
 * custom class).
 */
final class RegisterMiddlewares
{
    /**
     * Adds middlewares to Slim app instance.
     *
     * @param \Slim\App $app app instance
     */
    public function __invoke(\Slim\App $app): void
    {
        // Parse json, form data and xml
        $app->addBodyParsingMiddleware();

        // Add Routing Middleware
        $app->addRoutingMiddleware();

        // Add Error Middleware
        $app->add(\Slim\Middleware\ErrorMiddleware::class);

        $basePath = $app->getBasePath();

        $app->add(new \Tuupola\Middleware\HttpBasicAuthentication([
            'relaxed' => ['localhost', 'multiflexi.local'],
            'path' => $basePath,
            'ignore' => [$basePath.'/login', $basePath.'/ping'],
            'authenticator' => static function ($arguments) {
                $prober = \Ease\Shared::user(null, '\MultiFlexi\User');

                if ($prober->isLogged()) {
                    return true;
                }

                $prober->loadFromSQL(['login' => $arguments['user']]);

                return $prober->isAccountEnabled() && $prober->passwordValidation($arguments['password'], $prober->getDataValue($prober->passwordColumn));
            },
        ]));

        // Bearer-token auth for service integrations (e.g. Node-RED). Added
        // AFTER HttpBasicAuthentication so it runs FIRST (Slim executes
        // middleware in reverse of add-order): a valid token logs the user
        // in via Ease\Shared so the Basic-auth layer below sees
        // isLogged() === true and skips the password check. No token
        // present -> fall through to Basic auth unchanged. A
        // present-but-invalid/expired token is rejected outright rather
        // than silently falling back to Basic.
        $app->add(new \Dyorg\TokenAuthentication([
            'secure' => true,
            'relaxed' => ['localhost', 'multiflexi.local'],
            'path' => $basePath,
            'except' => [$basePath.'/login', $basePath.'/ping'],
            'authenticator' => static function ($request, \Dyorg\TokenAuthentication\TokenSearch $tokenSearch) {
                try {
                    $tokenString = $tokenSearch->getToken($request);
                } catch (\Dyorg\TokenAuthentication\Exceptions\TokenNotFoundException $exc) {
                    // No bearer token on this request - let Basic auth handle it.
                    return true;
                }

                $token = new \MultiFlexi\Token();
                $token->loadFromSQL(['token' => $tokenString]);

                if ($token->isValid() === false) {
                    throw new \Dyorg\TokenAuthentication\Exceptions\UnauthorizedException('Invalid or expired token');
                }

                \Ease\Shared::user($token->getUser());

                return true;
            },
        ]));
    }
}
