#!/bin/sh
set -e

case "$1" in
    configure)
        mkdir -p /var/log/multiflexi-server
        chown root:www-data /var/log/multiflexi-server
        chmod 775 /var/log/multiflexi-server
        mkdir -p /etc/multiflexi-server
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
