<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * AppTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\App
 */
class AppTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "App".
     */
    public function testApp(): void
    {
        $testApp = new App();
        $namespacedClassname = App::getModelsNamespace().'\\App';
        $this->assertSame('\\'.App::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId(): void
    {
        self::markTestIncomplete(
            'Test of "id" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "enabled".
     */
    public function testPropertyEnabled(): void
    {
        self::markTestIncomplete(
            'Test of "enabled" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "image".
     */
    public function testPropertyImage(): void
    {
        self::markTestIncomplete(
            'Test of "image" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName(): void
    {
        self::markTestIncomplete(
            'Test of "name" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "description".
     */
    public function testPropertyDescription(): void
    {
        self::markTestIncomplete(
            'Test of "description" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "executable".
     */
    public function testPropertyExecutable(): void
    {
        self::markTestIncomplete(
            'Test of "executable" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "datCreate".
     */
    public function testPropertyDatCreate(): void
    {
        self::markTestIncomplete(
            'Test of "datCreate" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "datUpdate".
     */
    public function testPropertyDatUpdate(): void
    {
        self::markTestIncomplete(
            'Test of "datUpdate" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "setup".
     */
    public function testPropertySetup(): void
    {
        self::markTestIncomplete(
            'Test of "setup" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "cmdparams".
     */
    public function testPropertyCmdparams(): void
    {
        self::markTestIncomplete(
            'Test of "cmdparams" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "deploy".
     */
    public function testPropertyDeploy(): void
    {
        self::markTestIncomplete(
            'Test of "deploy" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "homepage".
     */
    public function testPropertyHomepage(): void
    {
        self::markTestIncomplete(
            'Test of "homepage" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "requirements".
     */
    public function testPropertyRequirements(): void
    {
        self::markTestIncomplete(
            'Test of "requirements" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "ociimage".
     */
    public function testPropertyOciimage(): void
    {
        self::markTestIncomplete(
            'Test of "ociimage" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "version".
     */
    public function testPropertyVersion(): void
    {
        self::markTestIncomplete(
            'Test of "version" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "code".
     */
    public function testPropertyCode(): void
    {
        self::markTestIncomplete(
            'Test of "code" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "uuid".
     */
    public function testPropertyUuid(): void
    {
        self::markTestIncomplete(
            'Test of "uuid" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "topics".
     */
    public function testPropertyTopics(): void
    {
        self::markTestIncomplete(
            'Test of "topics" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "resultfile".
     */
    public function testPropertyResultfile(): void
    {
        self::markTestIncomplete(
            'Test of "resultfile" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "artifacts".
     */
    public function testPropertyArtifacts(): void
    {
        self::markTestIncomplete(
            'Test of "artifacts" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "environment".
     */
    public function testPropertyEnvironment(): void
    {
        self::markTestIncomplete(
            'Test of "environment" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "exitCodes".
     */
    public function testPropertyExitCodes(): void
    {
        self::markTestIncomplete(
            'Test of "exitCodes" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "tags".
     */
    public function testPropertyTags(): void
    {
        self::markTestIncomplete(
            'Test of "tags" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "status".
     */
    public function testPropertyStatus(): void
    {
        self::markTestIncomplete(
            'Test of "status" property in "App" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = App::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
