<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 * The version of the OpenAPI document: 1.1.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * CompanyTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\Company
 */
class CompanyTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "Company".
     */
    public function testCompany(): void
    {
        $testCompany = new Company();
        $namespacedClassname = Company::getModelsNamespace().'\\Company';
        $this->assertSame('\\'.Company::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId(): void
    {
        self::markTestIncomplete(
            'Test of "id" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "enabled".
     */
    public function testPropertyEnabled(): void
    {
        self::markTestIncomplete(
            'Test of "enabled" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "settings".
     */
    public function testPropertySettings(): void
    {
        self::markTestIncomplete(
            'Test of "settings" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "logo".
     */
    public function testPropertyLogo(): void
    {
        self::markTestIncomplete(
            'Test of "logo" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "server".
     */
    public function testPropertyServer(): void
    {
        self::markTestIncomplete(
            'Test of "server" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName(): void
    {
        self::markTestIncomplete(
            'Test of "name" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "ic".
     */
    public function testPropertyIc(): void
    {
        self::markTestIncomplete(
            'Test of "ic" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "company".
     */
    public function testPropertyCompany(): void
    {
        self::markTestIncomplete(
            'Test of "company" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "rw".
     */
    public function testPropertyRw(): void
    {
        self::markTestIncomplete(
            'Test of "rw" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "setup".
     */
    public function testPropertySetup(): void
    {
        self::markTestIncomplete(
            'Test of "setup" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "webhook".
     */
    public function testPropertyWebhook(): void
    {
        self::markTestIncomplete(
            'Test of "webhook" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "datCreate".
     */
    public function testPropertyDatCreate(): void
    {
        self::markTestIncomplete(
            'Test of "datCreate" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "datUpdate".
     */
    public function testPropertyDatUpdate(): void
    {
        self::markTestIncomplete(
            'Test of "datUpdate" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "customer".
     */
    public function testPropertyCustomer(): void
    {
        self::markTestIncomplete(
            'Test of "customer" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "email".
     */
    public function testPropertyEmail(): void
    {
        self::markTestIncomplete(
            'Test of "email" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "code".
     */
    public function testPropertyCode(): void
    {
        self::markTestIncomplete(
            'Test of "code" property in "Company" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = Company::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
