<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.2.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * DataExportDataCredentialsInnerTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\DataExportDataCredentialsInner
 */
class DataExportDataCredentialsInnerTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "DataExportDataCredentialsInner".
     */
    public function testDataExportDataCredentialsInner(): void
    {
        $testDataExportDataCredentialsInner = new DataExportDataCredentialsInner();
        $namespacedClassname = DataExportDataCredentialsInner::getModelsNamespace().'\\DataExportDataCredentialsInner';
        $this->assertSame('\\'.DataExportDataCredentialsInner::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "DataExportDataCredentialsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "credentialId".
     */
    public function testPropertyCredentialId(): void
    {
        self::markTestIncomplete(
            'Test of "credentialId" property in "DataExportDataCredentialsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "credentialName".
     */
    public function testPropertyCredentialName(): void
    {
        self::markTestIncomplete(
            'Test of "credentialName" property in "DataExportDataCredentialsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "companyId".
     */
    public function testPropertyCompanyId(): void
    {
        self::markTestIncomplete(
            'Test of "companyId" property in "DataExportDataCredentialsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "credentialType".
     */
    public function testPropertyCredentialType(): void
    {
        self::markTestIncomplete(
            'Test of "credentialType" property in "DataExportDataCredentialsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "note".
     */
    public function testPropertyNote(): void
    {
        self::markTestIncomplete(
            'Test of "note" property in "DataExportDataCredentialsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = DataExportDataCredentialsInner::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
