<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * DataExportDataUserProfileTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\DataExportDataUserProfile
 */
class DataExportDataUserProfileTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "DataExportDataUserProfile".
     */
    public function testDataExportDataUserProfile(): void
    {
        $testDataExportDataUserProfile = new DataExportDataUserProfile();
        $namespacedClassname = DataExportDataUserProfile::getModelsNamespace().'\\DataExportDataUserProfile';
        $this->assertSame('\\'.DataExportDataUserProfile::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "DataExportDataUserProfile" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "userId".
     */
    public function testPropertyUserId(): void
    {
        self::markTestIncomplete(
            'Test of "userId" property in "DataExportDataUserProfile" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "username".
     */
    public function testPropertyUsername(): void
    {
        self::markTestIncomplete(
            'Test of "username" property in "DataExportDataUserProfile" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "email".
     */
    public function testPropertyEmail(): void
    {
        self::markTestIncomplete(
            'Test of "email" property in "DataExportDataUserProfile" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "firstName".
     */
    public function testPropertyFirstName(): void
    {
        self::markTestIncomplete(
            'Test of "firstName" property in "DataExportDataUserProfile" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "lastName".
     */
    public function testPropertyLastName(): void
    {
        self::markTestIncomplete(
            'Test of "lastName" property in "DataExportDataUserProfile" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "accountEnabled".
     */
    public function testPropertyAccountEnabled(): void
    {
        self::markTestIncomplete(
            'Test of "accountEnabled" property in "DataExportDataUserProfile" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "accountCreated".
     */
    public function testPropertyAccountCreated(): void
    {
        self::markTestIncomplete(
            'Test of "accountCreated" property in "DataExportDataUserProfile" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "lastUpdated".
     */
    public function testPropertyLastUpdated(): void
    {
        self::markTestIncomplete(
            'Test of "lastUpdated" property in "DataExportDataUserProfile" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "userSettings".
     */
    public function testPropertyUserSettings(): void
    {
        self::markTestIncomplete(
            'Test of "userSettings" property in "DataExportDataUserProfile" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = DataExportDataUserProfile::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
