<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * DataExportDataConsentRecordsConsentRecordsInnerTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\DataExportDataConsentRecordsConsentRecordsInner
 */
class DataExportDataConsentRecordsConsentRecordsInnerTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "DataExportDataConsentRecordsConsentRecordsInner".
     */
    public function testDataExportDataConsentRecordsConsentRecordsInner(): void
    {
        $testDataExportDataConsentRecordsConsentRecordsInner = new DataExportDataConsentRecordsConsentRecordsInner();
        $namespacedClassname = DataExportDataConsentRecordsConsentRecordsInner::getModelsNamespace().'\\DataExportDataConsentRecordsConsentRecordsInner';
        $this->assertSame('\\'.DataExportDataConsentRecordsConsentRecordsInner::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "DataExportDataConsentRecordsConsentRecordsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "consentId".
     */
    public function testPropertyConsentId(): void
    {
        self::markTestIncomplete(
            'Test of "consentId" property in "DataExportDataConsentRecordsConsentRecordsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "consentType".
     */
    public function testPropertyConsentType(): void
    {
        self::markTestIncomplete(
            'Test of "consentType" property in "DataExportDataConsentRecordsConsentRecordsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "status".
     */
    public function testPropertyStatus(): void
    {
        self::markTestIncomplete(
            'Test of "status" property in "DataExportDataConsentRecordsConsentRecordsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "details".
     */
    public function testPropertyDetails(): void
    {
        self::markTestIncomplete(
            'Test of "details" property in "DataExportDataConsentRecordsConsentRecordsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "policyVersion".
     */
    public function testPropertyPolicyVersion(): void
    {
        self::markTestIncomplete(
            'Test of "policyVersion" property in "DataExportDataConsentRecordsConsentRecordsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "grantedAt".
     */
    public function testPropertyGrantedAt(): void
    {
        self::markTestIncomplete(
            'Test of "grantedAt" property in "DataExportDataConsentRecordsConsentRecordsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "expiresAt".
     */
    public function testPropertyExpiresAt(): void
    {
        self::markTestIncomplete(
            'Test of "expiresAt" property in "DataExportDataConsentRecordsConsentRecordsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "withdrawnAt".
     */
    public function testPropertyWithdrawnAt(): void
    {
        self::markTestIncomplete(
            'Test of "withdrawnAt" property in "DataExportDataConsentRecordsConsentRecordsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "ipAddress".
     */
    public function testPropertyIpAddress(): void
    {
        self::markTestIncomplete(
            'Test of "ipAddress" property in "DataExportDataConsentRecordsConsentRecordsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = DataExportDataConsentRecordsConsentRecordsInner::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
