<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * DataExportDataJobHistoryInnerTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\DataExportDataJobHistoryInner
 */
class DataExportDataJobHistoryInnerTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "DataExportDataJobHistoryInner".
     */
    public function testDataExportDataJobHistoryInner(): void
    {
        $testDataExportDataJobHistoryInner = new DataExportDataJobHistoryInner();
        $namespacedClassname = DataExportDataJobHistoryInner::getModelsNamespace().'\\DataExportDataJobHistoryInner';
        $this->assertSame('\\'.DataExportDataJobHistoryInner::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "DataExportDataJobHistoryInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "jobId".
     */
    public function testPropertyJobId(): void
    {
        self::markTestIncomplete(
            'Test of "jobId" property in "DataExportDataJobHistoryInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "applicationId".
     */
    public function testPropertyApplicationId(): void
    {
        self::markTestIncomplete(
            'Test of "applicationId" property in "DataExportDataJobHistoryInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "companyId".
     */
    public function testPropertyCompanyId(): void
    {
        self::markTestIncomplete(
            'Test of "companyId" property in "DataExportDataJobHistoryInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "startedAt".
     */
    public function testPropertyStartedAt(): void
    {
        self::markTestIncomplete(
            'Test of "startedAt" property in "DataExportDataJobHistoryInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "completedAt".
     */
    public function testPropertyCompletedAt(): void
    {
        self::markTestIncomplete(
            'Test of "completedAt" property in "DataExportDataJobHistoryInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "exitCode".
     */
    public function testPropertyExitCode(): void
    {
        self::markTestIncomplete(
            'Test of "exitCode" property in "DataExportDataJobHistoryInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "status".
     */
    public function testPropertyStatus(): void
    {
        self::markTestIncomplete(
            'Test of "status" property in "DataExportDataJobHistoryInner" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = DataExportDataJobHistoryInner::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
