<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.2.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * DataExportDataTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\DataExportData
 */
class DataExportDataTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "DataExportData".
     */
    public function testDataExportData(): void
    {
        $testDataExportData = new DataExportData();
        $namespacedClassname = DataExportData::getModelsNamespace().'\\DataExportData';
        $this->assertSame('\\'.DataExportData::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "DataExportData" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "exportMetadata".
     */
    public function testPropertyExportMetadata(): void
    {
        self::markTestIncomplete(
            'Test of "exportMetadata" property in "DataExportData" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "userProfile".
     */
    public function testPropertyUserProfile(): void
    {
        self::markTestIncomplete(
            'Test of "userProfile" property in "DataExportData" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "companyAssociations".
     */
    public function testPropertyCompanyAssociations(): void
    {
        self::markTestIncomplete(
            'Test of "companyAssociations" property in "DataExportData" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "credentials".
     */
    public function testPropertyCredentials(): void
    {
        self::markTestIncomplete(
            'Test of "credentials" property in "DataExportData" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "activityLogs".
     */
    public function testPropertyActivityLogs(): void
    {
        self::markTestIncomplete(
            'Test of "activityLogs" property in "DataExportData" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "jobHistory".
     */
    public function testPropertyJobHistory(): void
    {
        self::markTestIncomplete(
            'Test of "jobHistory" property in "DataExportData" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "consentRecords".
     */
    public function testPropertyConsentRecords(): void
    {
        self::markTestIncomplete(
            'Test of "consentRecords" property in "DataExportData" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "sessionHistory".
     */
    public function testPropertySessionHistory(): void
    {
        self::markTestIncomplete(
            'Test of "sessionHistory" property in "DataExportData" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "auditTrails".
     */
    public function testPropertyAuditTrails(): void
    {
        self::markTestIncomplete(
            'Test of "auditTrails" property in "DataExportData" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = DataExportData::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
