<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * DataExportDataCompanyAssociationsInnerTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\DataExportDataCompanyAssociationsInner
 */
class DataExportDataCompanyAssociationsInnerTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "DataExportDataCompanyAssociationsInner".
     */
    public function testDataExportDataCompanyAssociationsInner(): void
    {
        $testDataExportDataCompanyAssociationsInner = new DataExportDataCompanyAssociationsInner();
        $namespacedClassname = DataExportDataCompanyAssociationsInner::getModelsNamespace().'\\DataExportDataCompanyAssociationsInner';
        $this->assertSame('\\'.DataExportDataCompanyAssociationsInner::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "DataExportDataCompanyAssociationsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "companyId".
     */
    public function testPropertyCompanyId(): void
    {
        self::markTestIncomplete(
            'Test of "companyId" property in "DataExportDataCompanyAssociationsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "companyCode".
     */
    public function testPropertyCompanyCode(): void
    {
        self::markTestIncomplete(
            'Test of "companyCode" property in "DataExportDataCompanyAssociationsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "companyName".
     */
    public function testPropertyCompanyName(): void
    {
        self::markTestIncomplete(
            'Test of "companyName" property in "DataExportDataCompanyAssociationsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "companyIdentifier".
     */
    public function testPropertyCompanyIdentifier(): void
    {
        self::markTestIncomplete(
            'Test of "companyIdentifier" property in "DataExportDataCompanyAssociationsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "enabled".
     */
    public function testPropertyEnabled(): void
    {
        self::markTestIncomplete(
            'Test of "enabled" property in "DataExportDataCompanyAssociationsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "associatedSince".
     */
    public function testPropertyAssociatedSince(): void
    {
        self::markTestIncomplete(
            'Test of "associatedSince" property in "DataExportDataCompanyAssociationsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "relationshipType".
     */
    public function testPropertyRelationshipType(): void
    {
        self::markTestIncomplete(
            'Test of "relationshipType" property in "DataExportDataCompanyAssociationsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = DataExportDataCompanyAssociationsInner::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
