<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.2.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * DataExportDataActivityLogsInnerTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\DataExportDataActivityLogsInner
 */
class DataExportDataActivityLogsInnerTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "DataExportDataActivityLogsInner".
     */
    public function testDataExportDataActivityLogsInner(): void
    {
        $testDataExportDataActivityLogsInner = new DataExportDataActivityLogsInner();
        $namespacedClassname = DataExportDataActivityLogsInner::getModelsNamespace().'\\DataExportDataActivityLogsInner';
        $this->assertSame('\\'.DataExportDataActivityLogsInner::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "DataExportDataActivityLogsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "logId".
     */
    public function testPropertyLogId(): void
    {
        self::markTestIncomplete(
            'Test of "logId" property in "DataExportDataActivityLogsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "companyId".
     */
    public function testPropertyCompanyId(): void
    {
        self::markTestIncomplete(
            'Test of "companyId" property in "DataExportDataActivityLogsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "applicationId".
     */
    public function testPropertyApplicationId(): void
    {
        self::markTestIncomplete(
            'Test of "applicationId" property in "DataExportDataActivityLogsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "severity".
     */
    public function testPropertySeverity(): void
    {
        self::markTestIncomplete(
            'Test of "severity" property in "DataExportDataActivityLogsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "source".
     */
    public function testPropertySource(): void
    {
        self::markTestIncomplete(
            'Test of "source" property in "DataExportDataActivityLogsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "message".
     */
    public function testPropertyMessage(): void
    {
        self::markTestIncomplete(
            'Test of "message" property in "DataExportDataActivityLogsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "timestamp".
     */
    public function testPropertyTimestamp(): void
    {
        self::markTestIncomplete(
            'Test of "timestamp" property in "DataExportDataActivityLogsInner" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = DataExportDataActivityLogsInner::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
