<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * EventRuleTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\EventRule
 */
class EventRuleTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "EventRule".
     */
    public function testEventRule(): void
    {
        $testEventRule = new EventRule();
        $namespacedClassname = EventRule::getModelsNamespace().'\\EventRule';
        $this->assertSame('\\'.EventRule::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "EventRule" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId(): void
    {
        self::markTestIncomplete(
            'Test of "id" property in "EventRule" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "eventSourceId".
     */
    public function testPropertyEventSourceId(): void
    {
        self::markTestIncomplete(
            'Test of "eventSourceId" property in "EventRule" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "evidence".
     */
    public function testPropertyEvidence(): void
    {
        self::markTestIncomplete(
            'Test of "evidence" property in "EventRule" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "operation".
     */
    public function testPropertyOperation(): void
    {
        self::markTestIncomplete(
            'Test of "operation" property in "EventRule" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "runtemplateId".
     */
    public function testPropertyRuntemplateId(): void
    {
        self::markTestIncomplete(
            'Test of "runtemplateId" property in "EventRule" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "priority".
     */
    public function testPropertyPriority(): void
    {
        self::markTestIncomplete(
            'Test of "priority" property in "EventRule" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "enabled".
     */
    public function testPropertyEnabled(): void
    {
        self::markTestIncomplete(
            'Test of "enabled" property in "EventRule" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "envMapping".
     */
    public function testPropertyEnvMapping(): void
    {
        self::markTestIncomplete(
            'Test of "envMapping" property in "EventRule" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "created".
     */
    public function testPropertyCreated(): void
    {
        self::markTestIncomplete(
            'Test of "created" property in "EventRule" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "modified".
     */
    public function testPropertyModified(): void
    {
        self::markTestIncomplete(
            'Test of "modified" property in "EventRule" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = EventRule::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
