<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * EventSourceTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\EventSource
 */
class EventSourceTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "EventSource".
     */
    public function testEventSource(): void
    {
        $testEventSource = new EventSource();
        $namespacedClassname = EventSource::getModelsNamespace().'\\EventSource';
        $this->assertSame('\\'.EventSource::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId(): void
    {
        self::markTestIncomplete(
            'Test of "id" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName(): void
    {
        self::markTestIncomplete(
            'Test of "name" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "adapterType".
     */
    public function testPropertyAdapterType(): void
    {
        self::markTestIncomplete(
            'Test of "adapterType" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "dbConnection".
     */
    public function testPropertyDbConnection(): void
    {
        self::markTestIncomplete(
            'Test of "dbConnection" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "dbHost".
     */
    public function testPropertyDbHost(): void
    {
        self::markTestIncomplete(
            'Test of "dbHost" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "dbPort".
     */
    public function testPropertyDbPort(): void
    {
        self::markTestIncomplete(
            'Test of "dbPort" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "dbDatabase".
     */
    public function testPropertyDbDatabase(): void
    {
        self::markTestIncomplete(
            'Test of "dbDatabase" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "dbUsername".
     */
    public function testPropertyDbUsername(): void
    {
        self::markTestIncomplete(
            'Test of "dbUsername" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "dbPassword".
     */
    public function testPropertyDbPassword(): void
    {
        self::markTestIncomplete(
            'Test of "dbPassword" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "pollInterval".
     */
    public function testPropertyPollInterval(): void
    {
        self::markTestIncomplete(
            'Test of "pollInterval" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "enabled".
     */
    public function testPropertyEnabled(): void
    {
        self::markTestIncomplete(
            'Test of "enabled" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "lastProcessedId".
     */
    public function testPropertyLastProcessedId(): void
    {
        self::markTestIncomplete(
            'Test of "lastProcessedId" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "created".
     */
    public function testPropertyCreated(): void
    {
        self::markTestIncomplete(
            'Test of "created" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "modified".
     */
    public function testPropertyModified(): void
    {
        self::markTestIncomplete(
            'Test of "modified" property in "EventSource" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = EventSource::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
