<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * RbacRoleTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\RbacRole
 */
class RbacRoleTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "RbacRole".
     */
    public function testRbacRole(): void
    {
        $testRbacRole = new RbacRole();
        $namespacedClassname = RbacRole::getModelsNamespace().'\\RbacRole';
        $this->assertSame('\\'.RbacRole::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete('Test of "RbacRole" model has not been implemented yet.');
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId(): void
    {
        self::markTestIncomplete('Test of "id" property in "RbacRole" model has not been implemented yet.');
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName(): void
    {
        self::markTestIncomplete('Test of "name" property in "RbacRole" model has not been implemented yet.');
    }

    /**
     * Test attribute "displayName".
     */
    public function testPropertyDisplayName(): void
    {
        self::markTestIncomplete('Test of "displayName" property in "RbacRole" model has not been implemented yet.');
    }

    /**
     * Test attribute "isActive".
     */
    public function testPropertyIsActive(): void
    {
        self::markTestIncomplete('Test of "isActive" property in "RbacRole" model has not been implemented yet.');
    }

    /**
     * Test attribute "assignedAt".
     */
    public function testPropertyAssignedAt(): void
    {
        self::markTestIncomplete('Test of "assignedAt" property in "RbacRole" model has not been implemented yet.');
    }

    /**
     * Test attribute "expiresAt".
     */
    public function testPropertyExpiresAt(): void
    {
        self::markTestIncomplete('Test of "expiresAt" property in "RbacRole" model has not been implemented yet.');
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = RbacRole::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
