<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.3.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateRunTemplateByIdRequestTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\UpdateRunTemplateByIdRequest
 */
class UpdateRunTemplateByIdRequestTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "UpdateRunTemplateByIdRequest".
     */
    public function testUpdateRunTemplateByIdRequest(): void
    {
        $testUpdateRunTemplateByIdRequest = new UpdateRunTemplateByIdRequest();
        $namespacedClassname = UpdateRunTemplateByIdRequest::getModelsNamespace().'\\UpdateRunTemplateByIdRequest';
        $this->assertSame('\\'.UpdateRunTemplateByIdRequest::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete(
            'Test of "UpdateRunTemplateByIdRequest" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "id".
     */
    public function testPropertyId(): void
    {
        self::markTestIncomplete(
            'Test of "id" property in "UpdateRunTemplateByIdRequest" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "active".
     */
    public function testPropertyActive(): void
    {
        self::markTestIncomplete(
            'Test of "active" property in "UpdateRunTemplateByIdRequest" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "interv".
     */
    public function testPropertyInterv(): void
    {
        self::markTestIncomplete(
            'Test of "interv" property in "UpdateRunTemplateByIdRequest" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName(): void
    {
        self::markTestIncomplete(
            'Test of "name" property in "UpdateRunTemplateByIdRequest" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "delay".
     */
    public function testPropertyDelay(): void
    {
        self::markTestIncomplete(
            'Test of "delay" property in "UpdateRunTemplateByIdRequest" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "executor".
     */
    public function testPropertyExecutor(): void
    {
        self::markTestIncomplete(
            'Test of "executor" property in "UpdateRunTemplateByIdRequest" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "cron".
     */
    public function testPropertyCron(): void
    {
        self::markTestIncomplete(
            'Test of "cron" property in "UpdateRunTemplateByIdRequest" model has not been implemented yet.',
        );
    }

    /**
     * Test attribute "note".
     */
    public function testPropertyNote(): void
    {
        self::markTestIncomplete(
            'Test of "note" property in "UpdateRunTemplateByIdRequest" model has not been implemented yet.',
        );
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = UpdateRunTemplateByIdRequest::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
