<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * MultiFlexi API provides comprehensive access to job execution, application management, event-driven processing, and user data operations. The API includes GDPR compliance endpoints for data export (Article 15 - Right of Access) and uses OAuth2 Application Flow for security.
 * The version of the OpenAPI document: 1.4.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://github.com/openapitools/openapi-generator.git.
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace MultiFlexi\Api\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateCredentialTypeRequestTest Class Doc Comment.
 *
 * @author  OpenAPI Generator team
 *
 * @see    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \MultiFlexi\Api\Model\UpdateCredentialTypeRequest
 */
class UpdateCredentialTypeRequestTest extends TestCase
{
    /**
     * Setup before running any test cases.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "UpdateCredentialTypeRequest".
     */
    public function testUpdateCredentialTypeRequest(): void
    {
        $testUpdateCredentialTypeRequest = new UpdateCredentialTypeRequest();
        $namespacedClassname = UpdateCredentialTypeRequest::getModelsNamespace().'\\UpdateCredentialTypeRequest';
        $this->assertSame('\\'.UpdateCredentialTypeRequest::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname),
        );
        self::markTestIncomplete('Test of "UpdateCredentialTypeRequest" model has not been implemented yet.');
    }

    /**
     * Test attribute "name".
     */
    public function testPropertyName(): void
    {
        self::markTestIncomplete('Test of "name" property in "UpdateCredentialTypeRequest" model has not been implemented yet.');
    }

    /**
     * Test attribute "description".
     */
    public function testPropertyDescription(): void
    {
        self::markTestIncomplete('Test of "description" property in "UpdateCredentialTypeRequest" model has not been implemented yet.');
    }

    /**
     * Test attribute "url".
     */
    public function testPropertyUrl(): void
    {
        self::markTestIncomplete('Test of "url" property in "UpdateCredentialTypeRequest" model has not been implemented yet.');
    }

    /**
     * Test attribute "logo".
     */
    public function testPropertyLogo(): void
    {
        self::markTestIncomplete('Test of "logo" property in "UpdateCredentialTypeRequest" model has not been implemented yet.');
    }

    /**
     * Test getOpenApiSchema static method.
     *
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema(): void
    {
        $schemaArr = UpdateCredentialTypeRequest::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
